{{- if $.Values.ipaserver.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.ipaserver.service }}
  namespace: {{ $.Values.ipaserver.namespace }}
spec:
  host: "{{ $.Values.ipaserver.service }}.{{ $.Values.app_domain }}"
  to:
    kind: Service
    name: {{ $.Values.ipaserver.service }}
  port:
    targetPort: https
  tls:
    termination: passthrough
  wildcardPolicy: None
{{- end }}