{{- if $.Values.ipaserver.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.ipaserver.service }}-password
  namespace: {{ $.Values.ipaserver.namespace }}
stringData:
  admin.password: {{ $.Values.ipaserver.password }}
{{- end }}