{{- if .Values.docs }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ .Values.docs.name }}"
  namespace: "{{ .Values.docs.namespace }}"
  labels:
    app: "{{ .Values.docs.name }}"
spec:
  to:
    kind: Service
    name: "{{ .Values.docs.name }}"
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge 
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
