{{- if $.Values.ipaserver.auth_ocp.enabled }}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  namespace: openshift-config
spec:
  identityProviders:
  - name: IPA_ldap
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - uid
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: {{ $.Values.ipaserver.auth_ocp.bind_dn }}
      bindPassword:
        name: {{ $.Values.ipaserver.service }}
      insecure: true
      url: 'ldap://{{ $.Values.ipaserver.service }}.{{ $.Values.ipaserver.namespace }}.svc.cluster.local/{{ $.Values.ipaserver.auth_ocp.base }}?uid'
{{- end }}
