{{- if $.Values.ipaserver.auth_ocp.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.ipaserver.service }}
  namespace: openshift-config
stringData:
  bindPassword: {{ $.Values.ipaserver.password }}
{{- end }}