{{- range $op := .Values.operators }}
{{- if $op.operatorgroup.create }}
{{- $og := $op.operatorgroup }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $op.name | default "tl500-operator-group" | quote }}
  namespace: {{ $op.namespace | quote }}
spec:
  targetNamespaces:
  - {{ $op.namespace }}
{{- end }}
{{- end }}
